# ==============
# WEB SCREENSHOT
# ==============

name: 'Web Screenshot Action'
description: 'Capture screenshot of a website'
author: 'Shresht7'

branding:
  icon: camera
  color: yellow

runs:
  using: 'node16'
  main: 'dist/index.js'

# Inputs
# ======

inputs:

  # URL
  # ---

  url:
    description: 'URL to take the screenshot of. [Required string]'
    required: true

  # Dimensions
  # ----------

  width:
    description: 'Viewport width. [number] (default: 1920)'
    default: 1920

  height:
    description: 'Viewport height. [number] (default: 1080)'
    default: 1080

  captureFullPage:
    description: 'Should take screenshot of the entire page. [boolean] (default: false)'
    default: false

  # Image File
  # ----------

  name:
    description: 'Screenshot filename. [string] (default: screenshot)'
    default: 'screenshot'

  type:
    description: 'Image file-type. [png, jpeg, webp] (default: png)'
    default: 'png'

  # Should Create Artifacts
  # -----------------------

  shouldCreateArtifacts:
    description: 'Should generate screenshot artifacts. [boolean] (default: false)'
    default: false