# ============================
#         SCREENSHOT
# ----------------------------
# Take screenshot of a website
# ============================

name: Screenshot

# Activation Events
# =================

on:
  workflow_dispatch:  # When a workflow event is dispatched manually

# Jobs
# ====

jobs:
  Screenshot:
    runs-on: ubuntu-latest
    
    name: Screenshot
    steps:
    
      # Actions/Checkout ✅
      # ===================

      # Required for GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v3

      # Take Screenshot 📷
      # ==================

      - name: Screenshot
        uses: Shresht7/web-screenshot-action@main
        id: Screenshot
        with:
          url: https://www.github.com/Shresht7/web-screenshot-action
          name: screenshot

      # Push to main 🌐
      # ===============

      - name: Commit
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add .
          git commit -m 'Update screenshot 📷'
          git push